### ISSUE TITLE
Remove model_classes methods

### ISSUE THREAD

**Issue by ianwhite** [ianwhite/orm_adapter#19]
The reason for OrmAdapter::Base.model_classes is historical, for pickle's requirement to generate a regexp matching all available models.

Pickle's not going be using this approach in future.

I think that this functionality cross-cuts orm_adapter's main concern, and so it should be removed.

@josevalim wdyt?

**Comment by josevalim** [comment]
:+1: for removing

## 

Sent from my iPhone
