### ISSUE TITLE
#assign_attributes method doesn't exist for MongoMapper:Document instances

### ISSUE THREAD

**Issue by lkalwa** [ianwhite/orm_adapter#21]
I'm not 100% sure this request should go here, or directly to MongoMapper maintainers.
Gems like devise are using this method (https://github.com/rails/rails/blob/32709ea41ed1ec2a89590e9bc6656c1ecd462d30/activerecord/lib/active_record/attribute_assignment.rb#L66) for about 3 months now and this problem is still quite burdensome for devise && mongo_mapper combination.

**Comment by ianwhite** [comment]
This is a very late response, so it may be out of date.

Is this the case: `#assign_attributes` is used by Devise on a model returned by `orm_adapter`?

If so, then this is outside of orm_adpater's current scope, as we just hand back the models without wrapping them, and hope they are ActiveModel compliant :)

Please reopen, or ping me if this is not the issue
