### ISSUE TITLE
create branch for activerecord (rails) 4

### ISSUE THREAD

**Issue by westonplatter** [ianwhite/orm_adapter#22]
I realize updating orm_adapter for activerecord4 compatibility will take some work. 

I started on it. See this [project/branch](https://github.com/westonplatter/orm_adapter/tree/rails4).

Could we create a rails4 changes on a separate branch? If you have a different organization preference, I am totally open to that too.

**Comment by freemanoid** [comment]
@westonplatter any news? Did you gave up this idea?

**Comment by westonplatter** [comment]
@freemanoid i started work on this to make devise compatible with Rails 4 ~14 months ago. I have since given up on this since devise is 100% compatible with Rails 4. I don't know if in this process Orm Adapter was made compatible with ActiveRecord 4. Hope that helps.

**Comment by freemanoid** [comment]
@westonplatter, orm_adapter isn't fully compatible with AR 4 now :\
https://github.com/plataformatec/devise/issues/2711

**Comment by ianwhite** [comment]
I'll have a look at this tomorrow morning. Pull requests welcome!

Sent from my iPhone

On 11 Nov 2013, at 21:40, freemanoid notifications@github.com wrote:

orm_adapter isn't fully compatible with AR 4 now :\
plataformatec/devise#2711https://github.com/plataformatec/devise/issues/2711

—
Reply to this email directly or view it on
GitHubhttps://github.com/ianwhite/orm_adapter/issues/22#issuecomment-28242127
.

**Comment by westonplatter** [comment]
@freemanoid wow, I was completely wrong. Sorry! Unfortunately I don't have time to work on PRs. :(

**Comment by ianwhite** [comment]
OK, I've got travis building against active_record 4, but none of the specs are failing.

Can someone give me a failing test case, or simply an example of use that causes orm_adapter to fail with active record 4?
