### ISSUE TITLE
ORM collection adapter

### ISSUE THREAD

**Issue by HoneyryderChuck** [ianwhite/orm_adapter#27]
First, great gem! I wasn't very aware of what was doing it for devise under the hood, but the need of such a tool led me here. It's still quite embryonic, but that's also a good thing.

I was wondering whether you would like to entertain the idea of also "adapting" collections. Current issues I have is the diverse API for such common stuff like scoping, build/create/destroy actions on it, class of its elements, batched search, among others. So, this would more a feature branch request than an issue.

**Comment by ianwhite** [comment]
Currently there are no plans to support something like this.  orm_adapter's scope is quite narrow on purpose.  We just aim to support the most basic factory like methods on ORM classes.

But, you could always implement your own adapter class using orm_adapter's infrastructure as a starting point.
