### ISSUE TITLE
Information / examples on how to create orm adapter gem

### ISSUE THREAD

**Issue by alexanderedge** [ianwhite/orm_adapter#29]
Hi there,

You've mentioned in #25 that a gem should be created to add support for other databases. Are you able to provide an example of how this can be done? I'm trying with  [CouchRest Model](https://github.com/couchrest/couchrest_model) but am getting te following error:

`cannot load such file -- orm_adapter/adapters/couchrest_model (LoadError)`

**Comment by ianwhite** [comment]
Hi there!

You can use the code in orm_adapter itself as an example of how to do it.  Look at `lib/orm_adapter/adapters/active_record.rb` and the associated specs as an example.

You might want to try forking orm_adapter, and adding your adapter into your version of orm_adapter, then extracting it when its specs are passing.  I just googled and found this recent orm_adapter plugin which could serve as an example: https://github.com/arukoh/orm_adapter-dynamoid

**Comment by alexanderedge** [comment]
Hi Ian,

Thanks a lot! I'll take a look at that example.

Alex  

## 

Alexander Edge
iOS Developer

+44 (0) 7732 077337
alexedge.co.uk (http://www.alexedge.co.uk)
@alexedge (https://twitter.com/alexedge)
