### ISSUE TITLE
Rails server not running due to ORM Adapter

### ISSUE THREAD

**Issue by kenan-memis** [ianwhite/orm_adapter#36]
Hi,

I am using Ubuntu 14.04, orm_adapter v.0.5, Rails 3.2.11 and ruby 1.9.3-2.0. 

After i run rails server command, I am getting the following warnings in rails console when I write localhost:3000 on browser and hit enter (No Data Received).

path_to_rvm_folder/gems/ruby-2.0.0-p247/gems/orm_adapter-0.5.0/lib/orm_adapter/adapters/active_record.rb:81: warning: already initialized constant ActiveRecord::Base::OrmAdapter

path_to_rvm_folder/gems/ruby-2.0.0-p247/gems/orm_adapter-0.5.0/lib/orm_adapter/adapters/active_record.rb:81: warning: previous definition of OrmAdapter was here

This happened after I upgraded my Ubuntu version from 13.10 to 14.04 but other projects on my pc are not having such a problem, they are working fine.

Any suggestions?

**Comment by sideshowcoder** [comment]
Seems like there is a conflict between 2 different version of orm_adapter trying to load, is this still a problem, or have you resolved this by now?

**Comment by ianwhite** [comment]
Hi, as @sideshowcoder points out, it looks like orm_adapter is being loaded twice (but it looks like the same version being loaded twice).  But, usually these warnings do not result in a failure.

Do you have any more info about this problem?

**Comment by eveadele** [comment]
I'm getting that same error with an app I'm upgrading to Rails 4. It only occurs when I try to run rspec tests, though; rails server works fine. I'm on Mac OS X so it's not just a Ubuntu issue. What could it be?

**Comment by ianwhite** [comment]
@eveadele is the warning causing rspec to fail, if so could you post the entire output of the failure?

I'm running a number of apps on 4.1, with devise & orm_adapter, and am not seeing the issue (so it's hard to troubleshoot).

**Comment by eveadele** [comment]
welp I think I figured it out, it was a problem with my test environment. Thanks for your help!

**Comment by enahs** [comment]
FWIW, make sure this is commented out in development.rb; caused hell for me.

``` ruby
config.active_record.auto_explain_threshold_in_seconds = 0.5
```

**Comment by blackham** [comment]
I'm in the process of upgrading some old old old apps built around Rail. 3.1.x => 4.1.6 and ruby 1.8.7 => 2.1.4. (I like pain). Two rails environments share the same modules and db/migration directory (to keep a common DB easier to replicate). One of the rails apps uses devise, the other does not. But the app that didn't use devise still had it in the Gemfile so it could load all the shared modules (even if it wasn't going to use them). In any case, the app that didn't use Devise upgraded with only lots of problems. The app that uses Devise had a lot more problems and is stuck currently with: 

(Excuse my lack of desire to learn markdown)

<addr>
rails c
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-4.1.6/lib/active_record/dynamic_matchers.rb:26:in `method_missing'/usr/local/rvm/gems/ruby-2.1.4/gems/orm_adapter-0.5.0/lib/orm_adapter/adapters/active_record.rb:81: warning: already initialized constant ActiveRecord::Base::OrmAdapter
/usr/local/rvm/gems/ruby-2.1.4/gems/orm_adapter-0.5.0/lib/orm_adapter/adapters/active_record.rb:81: warning: previous definition of OrmAdapter was here
: undefined method`whitelist_attributes=' for #Class:0x000000064ac260 (NoMethodError)
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-4.1.6/lib/active_record/railtie.rb:110:in `block (3 levels) in <class:Railtie>'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-4.1.6/lib/active_record/railtie.rb:109:in`each'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-4.1.6/lib/active_record/railtie.rb:109:in `block (2 levels) in <class:Railtie>'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/lazy_load_hooks.rb:38:in`instance_eval'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/lazy_load_hooks.rb:45:in`block in run_load_hooks'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/lazy_load_hooks.rb:44:in `each'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/lazy_load_hooks.rb:44:in`run_load_hooks'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-4.1.6/lib/active_record/base.rb:326:in `<module:ActiveRecord>'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-4.1.6/lib/active_record/base.rb:23:in`<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/devise-3.4.1/lib/devise/orm/active_record.rb:3:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in`require'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `block in require'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in`load_dependency'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
        from /home/brett/upgrade/internal/config/initializers/devise.rb:22:in`block in <top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/devise-3.4.1/lib/devise.rb:293:in `setup'
        from /home/brett/upgrade/internal/config/initializers/devise.rb:3:in`<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:241:in `load'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:241:in`block in load'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:241:in`load'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/engine.rb:648:in `block in load_config_initializer'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/notifications.rb:161:in`instrument'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/engine.rb:647:in `load_config_initializer'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/engine.rb:612:in`block (2 levels) in class:Engine'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/engine.rb:611:in `each'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/engine.rb:611:in`block in class:Engine'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/initializable.rb:30:in `instance_exec'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/initializable.rb:30:in`run'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:226:in`block in tsort_each'
        from /usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
        from /usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:418:in`block (2 levels) in each_strongly_connected_component_from'
        from /usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
        from /usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:417:in`block in each_strongly_connected_component_from'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/initializable.rb:44:in `each'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/initializable.rb:44:in`tsort_each_child'
        from /usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:411:in `call'
        from /usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:411:in`each_strongly_connected_component_from'
        from /usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
        from /usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:345:in`each'
        from /usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:345:in `call'
        from /usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:345:in`each_strongly_connected_component'
        from /usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
        from /usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:205:in`tsort_each'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/initializable.rb:54:in `run_initializers'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/application.rb:300:in`initialize!'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/railtie.rb:194:in `public_send'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/railtie.rb:194:in`method_missing'
        from /home/brett/upgrade/internal/config/environment.rb:5:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in`require'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `block in require'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in`load_dependency'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/application.rb:276:in`require_environment!'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:147:in `require_application_and_environment!'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:68:in`console'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/commands.rb:17:in`<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in`<main>'

**Comment by blackham** [comment]
rake rails:update fixed it.

(When I ran it the first time it was still using rails 3.1.x)

**Comment by ianwhite** [comment]
Thanks for posting back re: the resolution.  Might be handy for someone else :+1:

**Comment by sahilbathlaofficial** [comment]
@snowjob870 - Thanks a lot, worked like a charm

**Comment by mkanthan** [comment]
rake rails:udpate did not fix this for me.  It wants to change a bunch of files, many of which I had modified and don't want those changes which would overwrite mine.  Do you know which specific part of rails:update fixed this issue?
