### ISSUE TITLE
Plan to add #update, #save or #destroy methods?

### ISSUE THREAD

**Issue by jeroenvandijk** [ianwhite/orm_adapter#4]
Hi Ian,

I think this gem is a create initiative. I'm wondering though whether there is a plan to add extra methods such as #save, #update or #destroy method to the api. This seems to be necessary even for a gem such as devise. Although I guess #destroy and #save seem to be universally used for orms.

Looking forward to your thoughts.

Cheers,
Jeroen

**Comment by josevalim** [comment]
`save` is a tricky one because each ORMs has completely different semantics for save and trying to unifying them all will be hard, quite hard. I guess we could support destroy as long it works through a class level API (for example, `Post.destroy(1)`).

**Comment by fredwu** [comment]
`#destroy` is implemented in this pull request: https://github.com/ianwhite/orm_adapter/pull/15

**Comment by fredwu** [comment]
I had a quick look at the mongoid/mongomapper/dm docs, they all support `update_attributes`. Looks like we're okay to have `save` (and potentially `update` too). If you guys are okay with it, I'll take a crack at it in the next day or two. cc @josevalim @ianwhite

**Comment by josevalim** [comment]
Personally, I am not a fan of such. While they provide the same API, the behavior may be considerably different (how does it handle and save associations? what about callbacks? what if you want to skip validations? what happens if it fails?). We should not hide this under the same API as if it works the same.

**Comment by fredwu** [comment]
@josevalim As far as I can tell, they all fire callbacks, and I don't think we need to (or should) deal with associations in this context. I am sure we can offer a unified way of error handling. In terms of skipping validations - well, I haven't look at it, but for the initial implementation I'd just leave that out. At the end of day, if `update_attributes` is common enough in the major ORMs, we should implement it to make `orm_adapter` more useful. wdyt? :)

**Comment by josevalim** [comment]
Regarding associations, some of them autosave the associations, some of them may not. For instance, if I had to rely on that on Devise, I would rather provide a devise specific hook instead of relying on a third party.

**Comment by fredwu** [comment]
Ah I see, I was only thinking of the direct attributes of the current model. Would it be fair to limit the initial scope then to only the current model, without any associations consideration (by either detecting them if we can, or otherwise simply state this fact in the documentation)?

**Comment by josevalim** [comment]
The fact we cannot control this in most ORMs, it is just how it works internally. If we are going to say "we simply call update_attributes, please check the underlying ORM for its behavior", it is better to simply call `update_attributes` without using ORM adapter as a proxy (that's what Devise does btw for save).

**Comment by fredwu** [comment]
What if we introduce another method to specifically update attributes that are directly for the current model? I'm pushing for this because having the ability to update attributes is really handy, and for simple use cases, it's more than enough. :)

**Comment by ianwhite** [comment]
Is there a reason why Jose's suggestion about calling #update_attributes on the instance won't work in your case?

**Comment by ianwhite** [comment]
Are we agreed that this issue is to be closed?

Perhaps we could expand on the README which mentions "... that needs agnosticism beyond Active Model.".

Something along the lines of... "orm_adapter provides a consistent API for the class or 'factory' type methods of ORMs.  It does not attempt to unify the behaviour of model instances, this means that methods such as model.save, and model.valid? are beyond the scope of orm_adapter."

**Comment by josevalim** [comment]
:+1: for closing and extending the readme

## 

Sent from my iPhone
