### ISSUE TITLE
Column metadata

### ISSUE THREAD

**Issue by nevir** [ianwhite/orm_adapter#6]
Would it make sense to extend ORM Adapter to also abstract metadata about columns (basic types & related info)?  It would be very helpful for projects like a model admin, and anything else that needs a bit deeper introspection into the model's information.  I'm guessing this is a large undertaking, though...

I'm interested in the column base type (string, numeric, integer, boolean, date/time/datetime) - and also relations (as minimal as possible): cardinality & target model class

**Comment by probablykabari** [comment]
This is a good question, I came her to fork orm_adapter to see if doing that would work in line with the projects goal. It seems like it would be a simple thing for every adapter other than AR, since it doesn't define properties.

**Comment by josevalim** [comment]
ORM Adapter goal is to stay simple. It is not part of ORM Adapter goal to have an agnostic way to create models. It assumes the models are created and try to provide an unified interface to manipulate them.
