### ISSUE TITLE
mongoid master (3.0.0) removes klass.first(:conditions...)

### ISSUE THREAD

**Issue by fwoeck** [ianwhite/orm_adapter#9]
Hi,

the new mongoid master removes any options from klass.first, so line 32 in
lib/orm_adapter/adapters/mongoid.rb fails.

Changing

``` ruby
# @see OrmAdapter::Base#get
def get(id)
  klass.first(:conditions => { :id => wrap_key(id) })
end
```

to

``` ruby
# @see OrmAdapter::Base#get
def get(id)
  klass.where(:_id => wrap_key(id)).first
end
```

should work.
Best regards,
Frank

**Comment by ianwhite** [comment]
Hi Frank,

> klass.where(:_id => wrap_key(id)).first

I've confirmed this works on older versions of mongoid, so this should be fine.  I'll add this into 0.0.6

Thanks very much.

Cheers,
Ian
